# Generated by Django 2.0.3 on 2018-05-08 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import kanfan.util.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kanfan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bangumi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': '该番剧已经存在'}, help_text='番剧名称', max_length=200, unique=True, verbose_name='番剧名')),
                ('rss', models.URLField(error_messages={'unique': '该rss链接已经存在'}, help_text='rss链接', unique=True, verbose_name='rss订阅链接')),
                ('state', models.IntegerField(choices=[(1, '播出中'), (2, '已完结')])),
                ('season', models.IntegerField(choices=[(1, '春'), (2, '夏'), (3, '秋'), (4, '冬')])),
                ('year', models.IntegerField(validators=[kanfan.util.validators.YearValidator()])),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanfan.Account')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': '该集已经存在'}, help_text='单集名称', max_length=200, unique=True, verbose_name='单集名')),
                ('file', models.FilePathField(max_length=500)),
                ('torrent', models.FilePathField(max_length=500)),
                ('magnet', models.TextField()),
                ('state', models.IntegerField(choices=[(1, '正在准备视频文件'), (2, '视频文件准备完毕'), (3, '视频文件不存在')])),
                ('subtitle_file', models.FilePathField(max_length=500)),
                ('subtitle_torrent', models.FilePathField(max_length=500)),
                ('subtitle_magnet', models.TextField()),
                ('bangumi_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanfan.Bangumi')),
            ],
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField(choices=[(1, '追番中'), (2, '已补完')])),
                ('account_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanfan.Account')),
                ('bangumi_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanfan.Bangumi')),
                ('last_episode_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanfan.Episode')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
